package serban.stoenescu.bujor.src.symbols;

public enum SymbolTypes {
 JOKER,DISTRIBUTED,NORMAL1,NORMAL2,NORMAL3,NORMAL4,NORMAL5,NORMAL6,BLOCKED,
 CACAT,PISAT,UNT,MAZGA,ULEI,PATEU,FUTAI,ALUNECUS,MAINI_TAIETE,PICIOARE_TAIETE,CAUCIUC,CARICIOR,VOMIT_INTRUNA,FAC_LABA_INTRUNA,MA_CAC_INTRUNA,MA_PIS_INTRUNA,MI_E_RAU
 
}

